### ISSUE TITLE
I can't run this code.Hint that I'm missing some function (ICtSystem、ICtMpcOp etc.)

### ISSUE THREAD

**Issue by Faust-Wang** [PrakritTyagi/MPC_UAV#1]

**Comment by PrakritTyagi** [comment]
@Faust-Wang You need to add to path **Virtual Arena** for that to work. [https://github.com/andreaalessandretti/VirtualArena] . If you had already done it please show me the error in command window.

**Comment by Faust-Wang** [comment]
Thank you very much. It's working now.Is there a published paper or documentation for this code

**Comment by PrakritTyagi** [comment]
> Thank you very much. It's working now.Is there a published paper or documentation for this code

No not yet.
